service: customauthorizer
frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
 
functions:
  ca: 
    handler: authorizer.handler
   
  mock:
    handler: handler.test
    events:
      - http:
          method: get
          cors: false
          path: /test
          authorizer:
            name: ca
            identitySource: method.request.header.username, method.request.header.methodARN
            resultTtlInSeconds: 0
            type: request

# >>> url  = "https://k4vuqbroub.execute-api.us-east-1.amazonaws.com/dev/test"*"
# >>> arn = "arn:aws:execute-api:*:*:*/dev/*"
# >>> e = {"methodArn":arn,"username":"si3mshady"}
# >>> d = requests.get(url=url, headers=e)


#Elliott Arnold 
#Custom Authorizer Practice p2
#12-7-21
#7-11


